services:
  - type: web
    name: chucky-v3
    repo: https://github.com/M-axie/Chucky-V3.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
      - key: MODE
        value: "public"
      - key: LOG_MSG
        value: "false"
      - key: AUTO_STATUS_SEEN
        value: "false"
      - key: READ_MSG
        value: "false"
      - key: ALWAYS_ONLINE
        value: "false"
      - key: AUTO_BLOCK
        value: "true"
      - key: PORT
        value: "3000"
